server:
  port: 8080

spring: #springboot的配置
  datasource: #定义数据源
    db-type: MYSQL
    driver-class-name: com.mysql.cj.jdbc.Driver
    #127.0.0.1为本机测试的ip，3306是mysql的端口号。serverTimezone是定义时区，照抄就好，mysql高版本需要定义这些东西
    #useSSL也是某些高版本mysql需要问有没有用SSL连接
    url: jdbc:mysql://127.0.0.1:3306/alan?useSSL=false&autoReconnect=true&serverTimezone=GMT%2B8&characterEncoding=utf8&rewriteBatchedStatements=true
    username: root  #数据库用户名，root为管理员
    password: 123456 #该数据库用户的密码

    #测试库
    #url: jdbc:mysql://10.86.72.222:3311/bms?useSSL=false&autoReconnect=true&serverTimezone=GMT%2B8&characterEncoding=utf8&rewriteBatchedStatements=true
    #username: mysqlljb
    #password: abcd_1234

    #生产库
    #url: jdbc:mysql://10.86.72.116:3306/bms?useSSL=false&autoReconnect=true&serverTimezone=GMT%2B8&characterEncoding=utf8&rewriteBatchedStatements=true
    #username: mysqlljb
    #password: abcd_1234
  jpa:
    show-sql: true

mybatis:  #mybatyis的配置
  mapper-locations: classpath:mapper/*Mapper.xml #指定mapper的配置文件的路径是mapper文件夹下的所有 xml文件。
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
logging:
  level:
    com.gooann.Mapper: debug

BMS:
  URL:
    #OA测试地址
    billToOA: https://oa-test.infinitus-int.com/api/infinitusint/public/workflow/doCreateWorkflowRequest
    #OA生产地址
    #billToOA: https://oa.infinitus-int.com/api/infinitusint/public/workflow/doCreateWorkflowRequest