server:
  port: 8084

spring: #springboot的配置
  datasource: #定义数据源
    #下面这两个配置，可以在每次连接的时候判断一些连接是否有效
    druid.test-on-borrow: true
    druid.test-while-idle: true
    driver-class-name: oracle.jdbc.driver.OracleDriver

    #wms生产库
    #type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:oracle:thin:@(DESCRIPTION=(LOAD_BALANCE=ON)(FAILOVER=ON)(ADDRESS_LIST=(ADDRESS=(PROTOCOL=TCP)(HOST= wmsdbsvc.infinitus.com.cn)(PORT=1521)))(CONNECT_DATA=(SERVER=DEDICATED) (SERVICE_NAME=wmsdb) (FAILOVER_MODE=(TYPE=SELECT)(METHOD=BASIC))))
    username: wmexchange
    password: WMEXCHANGE

  jpa:
    show-sql: true

mybatis:  #mybatyis的配置
  mapper-locations: classpath:mapper/*Mapper.xml #指定mapper的配置文件的路径是mapper文件夹下的所有 xml文件。
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
logging:
  level:
    com.gooann.Mapper: debug
    #info/warn/trace: info/warn;
    com.staticzz: debug

BMS:
  URL:
    #OA测试地址-发起流程
    billToOA: https://oa-test.infinitus-int.com/api/infinitusint/public/workflow/doCreateWorkflowRequest

    #op准生产地址：
    bmsToOP: https://erp-trial.infinitus.com.cn/esop-op/admin/esb/op/accounting/ExpenseAccount


target:
  token:
    #BMS->OP秘钥
    bmsToOP: ESB-ESOP-SIGNATURE

#消费者秘钥与名称
wms:
  secret:
    value: JAWVKOEXCJRMVIHMDY0MG1L4RBLBJW6K
  keyId:
    value: wms
  url:
    value: https://gapi.infinitus.com.cn
  listskus:
    value: /product-api/skus
  ListCommodities:
    value: /product-api/commodities







